export const profiles = [
  {
    id: "1",
    name: "Carlos Rodríguez",
    username: "carlos_dev",
    avatar: "../../assets/cod-bg.jpg",
    banner: "../../assets/banner.jpg",
    bio: "Gamer apasionado por los RPG y las aventuras épicas. Más de 5 años jugando en PlayStation y coleccionista de ediciones especiales.",
    stats: {
      posts: 42,
      followers: 1024,
      following: 256,
      games: 87,
      reviews: 34,
    },
    categories: {
      Plataforma: ["PC", "PlayStation"],
      Género: ["RPG", "Aventura","accion"],
      Experiencia: ["Profesional"],
    },
  },
  {
    id: "2",
    name: "Ana Martínez",
    username: "ana_design",
    avatar: "../../assets/user1.jpg",
    banner: "../../assets/banner.jpg",
    bio: "Fanática de los juegos de Nintendo y las aventuras gráficas. Coleccionista de ediciones limitadas y figuras de videojuegos.",
    stats: {
      posts: 87,
      followers: 3200,
      following: 420,
      games: 65,
      reviews: 28,
    },
    categories: {
      Plataforma: ["PC", "Nintendo Switch"],
      Género: ["Aventura", "Simulación"],
      Experiencia: ["Profesional"],
    },
  },
  {
    id: "3",
    name: "Miguel López",
    username: "miguel_gamer",
    avatar: "../../assets/user3.jpg",
    banner: "../../assets/banner.jpg",
    bio: "Streamer de FPS y Battle Royale. Competidor profesional en torneos internacionales de Fortnite, Apex Legends y Call of Duty.",
    stats: {
      posts: 156,
      followers: 5600,
      following: 350,
      games: 42,
      reviews: 15,
    },
    categories: {
      Plataforma: ["PC", "Xbox", "PlayStation"],
      Género: ["FPS", "Battle Royale"],
      Experiencia: ["Streamer"],
    },
  },
  {
    id: "4",
    name: "Laura Sánchez",
    username: "laura_photo",
    avatar: "../../assets/user2.jpg",
    banner: "../../assets/banner.jpg",
    bio: "Jugadora casual de puzzles y juegos móviles. Fan de Animal Crossing y Zelda. Me encanta la fotografía virtual en juegos con buenos modos foto.",
    stats: {
      posts: 210,
      followers: 4300,
      following: 512,
      games: 38,
      reviews: 22,
    },
    categories: {
      Plataforma: ["Mobile", "Nintendo Switch"],
      Género: ["Casual", "Puzzle"],
      Experiencia: ["Aficionado"],
    },
  },
  {
    id: "5",
    name: "Javier Torres",
    username: "javi_music",
    avatar: "../../assets/user4.jpg",
    banner: "../../assets/banner.jpg",
    bio: "Especialista en juegos de ritmo y simulación. Coleccionista de ediciones especiales de PlayStation. Productor musical y DJ en mi tiempo libre.",
    stats: {
      posts: 95,
      followers: 2800,
      following: 430,
      games: 120,
      reviews: 45,
    },
    categories: {
      Plataforma: ["PC", "PlayStation"],
      Género: ["Ritmo", "Simulación"],
      Experiencia: ["Profesional"],
    },
  },
  {
    id: "6",
    name: "Tu Perfil",
    username: "mi_perfil",
    avatar: "../../assets/user5.jpeg",
    banner: "../../assets/banner.jpg",
    bio: "Este es tu perfil personalizado. ¡Edítalo para hacerlo único y mostrar tus juegos favoritos! Comparte tus experiencias y conecta con otros gamers.",
    stats: {
      posts: 0,
      followers: 0,
      following: 0,
      games: 0,
      reviews: 0,
    },
    categories: {
      Plataforma: ["PC"],
      Género: ["RPG"],
      Experiencia: ["Aficionado"],
    },
  },
];

export const filterCategories = [
  {
    name: "Plataforma",
    options: ["PC", "PlayStation", "Xbox", "Nintendo Switch", "Mobile"],
  },
  {
    name: "Género",
    options: [
      "RPG",
      "Aventura",
      "FPS",
      "Estrategia",
      "Simulación",
      "Deportes",
      "Puzzle",
      "Battle Royale",
      "Casual",
      "Ritmo",
    ],
  },
  {
    name: "Experiencia",
    options: ["Profesional", "Aficionado", "Streamer", "Competitivo", "Casual"],
  },
];
